### ISSUE TITLE
Not compatible with torch 1.2.0

### ISSUE THREAD

**Issue by DeiPlusAY** [locuslab/qpth#24]
In the torch document of 1.1.0 there is the following statement:
"LU factorization with pivot = False is not available for CPU, and attempting to do so will throw an error. However, LU factorization with pivot = False is available for CUDA."

So running torch 1.2.0 with the current qpth we found the following issue:

Traceback (most recent call last):
  File "/home/deiplusay/.local/lib/python3.7/site-packages/qpth/solvers/pdipm/batch.py", line 385, in pre_factor_kkt
    Q_LU = btrifact_hack(Q)
  File "/home/deiplusay/.local/lib/python3.7/site-packages/qpth/solvers/pdipm/batch.py", line 14, in btrifact_hack
    return x.btrifact(pivot=not x.is_cuda)
AttributeError: 'Tensor' object has no attribute 'btrifact'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "optnet_test.py", line 55, in <module>
    print(opt(torch.rand(16,100)))
  File "/home/deiplusay/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "optnet_test.py", line 50, in forward
    x = QPFunction(verbose=False)(Q, x, self.G, h, e, e)
  File "/home/deiplusay/.local/lib/python3.7/site-packages/qpth/qp.py", line 91, in forward
    self.Q_LU, self.S_LU, self.R = pdipm_b.pre_factor_kkt(Q, G, A)
  File "/home/deiplusay/.local/lib/python3.7/site-packages/qpth/solvers/pdipm/batch.py", line 391, in pre_factor_kkt
    """)

The proposed fix should replace btrifact() with torch.lu()

**Comment by bamos** [comment]
Thanks for sending this in! I fixed this about a month ago in master but didn't upload a new version to pypi -- just now pushed one. Can you pull 0.0.14 and re-open this issue and let me know if it doesn't work for you?
