### ISSUE TITLE
CVXPY not defined as dependency

### ISSUE THREAD

**Issue by WillemWybo** [locuslab/qpth#39]
Seems like CVXPY is not defined as a dependency. Package was successfully installed with pip, but got `ModuleNotFoundError: No module named 'cvxpy'` when trying to run it.

**Comment by cauchy7203** [comment]
The same issue appeared.

The source code calling qpth

``` python

import torch
from qpth.qp import QPFunction

slv = QPFunction()
```

Then the error reported:

```
Traceback (most recent call last):
  File "F:/GitPy/PythonProjects/LSSVM_Demos/demo_qpth.py", line 2, in <module>
    from Common_Models.qpth.qp import QPFunction
  File "F:\GitPy\PythonProjects\Common_Models\qpth\__init__.py", line 3, in <module>
    from . import qp
  File "F:\GitPy\PythonProjects\Common_Models\qpth\qp.py", line 5, in <module>
    from . import solvers
  File "F:\GitPy\PythonProjects\Common_Models\qpth\solvers\__init__.py", line 3, in <module>
    from . import cvxpy
  File "F:\GitPy\PythonProjects\Common_Models\qpth\solvers\cvxpy.py", line 1, in <module>
    import cvxpy as cp
ModuleNotFoundError: No module named 'cvxpy'

Process finished with exit code 1

```

**Comment by bamos** [comment]
Thanks, I've fixed this now
